### ISSUE TITLE
skip whitespace for different lexers

### ISSUE THREAD

**Issue by asmwarrior** [axilmar/parserlib#11]
I think for some kinds of low level lexer, the white space should not be skipped. But when parsing the high level Token, we should skip the white space. That's why the boost spirit has a skipper object as the parser input.

Can you have such kind of options? Thanks.

**Comment by axilmar** [comment]
Sure, a parser can easily be created that parses comments into documentation information, for example, conditionally, based on a flag specified either at run time or compile time.

The basic library is language-agnostic and will not provide language-specific functionality though.
