### ISSUE TITLE
homepage document improvement suggestion

### ISSUE THREAD

**Issue by asmwarrior** [axilmar/parserlib#12]
First, in the last section: https://github.com/axilmar/parserlib#resuming-from-errors

I suggest adding a real input string, so that the "resume from errors" can be more clear.

Second, in the first section: https://github.com/axilmar/parserlib#introduction
Especially in the code:

```
extern Rule<> add;

const auto val = +terminalRange('0', '9');

const auto num = val
               | '(' >> add >> ')';

Rule<> mul = mul >> '*' >> num
           | mul >> '/' >> num
           | num;

Rule<> add = add >> '+' >> mul
           | add >> '-' >> mul
           | mul;
```

I think you need to explain why the `extern Rule<> add;`, maybe adding some link to https://github.com/axilmar/parserlib#non-left-recursion, because in the section, it said `//forward declaration of recursive rule` in the comments.

BTW: look at the above code, why `mul` don't need a forward declaration? Is it because the definition and the reference is in the same statement?

**Comment by axilmar** [comment]
Thanks for the remarks.

Mul indeed doesn't need a forward declaration because by the time the expression contains mul, the compiler already knows of a variable named mul.

I will add those explanations as soon as I continue with the library, right now I am busy with work.

**Comment by asmwarrior** [comment]
Oh, I think the homepage document hasn't changed since I wrote the issue. Do you forget it? I see you have closed the issue.

**Comment by axilmar** [comment]
I had forgotten to commit the document; thanks for the reminder.
