### ISSUE TITLE
typo in homepage markdown file

### ISSUE THREAD

**Issue by asmwarrior** [axilmar/parserlib#15]
> providing extra information regarding the source, for example line and oclumn numbers.

It should be "column".

**Comment by asmwarrior** [comment]
~~~~
const auto a = terminal('A') == A;
const auto b = terminal('B') == B;
const auto c = terminal('B') == C;
~~~~

The last line should be 'C'.

**Comment by axilmar** [comment]
Fixed it, thanks for the tip.
