### ISSUE TITLE
A match id is always being a std::string?

### ISSUE THREAD

**Issue by asmwarrior** [axilmar/parserlib#7]
Hi, when I read the home page:

~~~~
const auto grammar = (-terminalSet('+', '-') >> terminalRange('0', '9')) == std::string("int");
std::string input = "123";
ParseContext<> pc(input);
const bool ok = grammar(pc);
for(const auto& match : pc.matches()) {
    if (match.id() == "int") {
	    const auto parsedString = match.content();
    	//process int
    }
}
~~~~

There is a condintion check:

~~~~
match.id() == "int"
~~~~

So, here comes my question: A match id is always be a std::string?

Thanks.

BTW: I'm also interested in develop a similar PEG like parsers in C++, see some of my idea here:

https://github.com/joemalle/limn/issues/10#issuecomment-1457534930

**Comment by asmwarrior** [comment]
It looks like the question is wrong here.

I just looked at the code: [cap/lexer.hpp at main · axilmar/cap](https://github.com/axilmar/cap/blob/main/include/lexer.hpp)

I see you have such code snippet:

~~~~
    /**
     * Token types.
     */
    enum class TOKEN {
        TYPEDEF,
        DOUBLE,
        STRUCT,
        CHAR,
        ENUM,
        VOID,
        INT,
        STRING,
        CHARACTER,
        IDENTIFIER,
        FLOAT,
        INTEGER,
        TILDE,
        BACKTICK,
        EXCLAMATION_MARK,
        AT_SIGN,
        NUMBER_SIGN,
        DOLLAR_SIGN,
        PERCENT,
        CARET,
        AMBERSAND,
        STAR,
        OPENING_PARENTHESIS,
        CLOSING_PARENTHESIS,
        UNDERSCORE,
        MINUS,
        PLUS,
        EQUALS,
        OPENING_CURLY_BRACKET,
        OPENING_SQUARE_BRACKET,
        CLOSING_CURLY_BRACKET,
        CLOSING_SQUARE_BRACKET,
        VERTICAL_BAR,
        BACKSLASH,
        COLON,
        SEMICOLON,
        DOUBLE_QUOTE,
        SINGLE_QUOTE,
        LESS_THAN,
        COMMA,
        GREATER_THAN,
        DOT,
        QUESTION_MARK,
        SLASH
    };
~~~~

And I see that in your rules definition:

https://github.com/axilmar/cap/blob/170efe84edc8b1f29620c89c8d2c7835a3b657b1/src/lexer.cpp#L31-L37

**Comment by axilmar** [comment]
Hi,

No, the match id can be configured statically as a template parameter of ParseContext.

I need to put that bit into the documentation.

**Comment by axilmar** [comment]
I added a paragraph in the documentation on how to customize the parse context.
